//file:noinspection GroovyAccessibility
//file:noinspection GroovyAssignabilityCheck
//file:noinspection DependencyNotationArgument

dependencies {
    // Fabric Loader
    modImplementation "net.fabricmc:fabric-loader:${rootProject.fabric_loader_version}"

    // Fabric API
    modImplementation "net.fabricmc.fabric-api:fabric-api:${rootProject.fabric_api_version}"

    // Architectury API
    modRuntimeOnly("dev.architectury:architectury-fabric:${rootProject.architectury_api_version}")

    // Mod Menu
    modRuntimeOnly "maven.modrinth:modmenu:${rootProject.mod_menu_version}"

    // Distant Horizons
    modRuntimeOnly("blank:DistantHorizons-${rootProject.distant_horizons_version}-${rootProject.minecraft_version}-neo-fabric")
}

loom {
    accessWidenerPath = project(":common").loom.accessWidenerPath
}
