//file:noinspection GroovyAccessibility
//file:noinspection GroovyAssignabilityCheck
//file:noinspection DependencyNotationArgument

loom {
    accessWidenerPath = project(":common").loom.accessWidenerPath
}

dependencies {
    // Architectury API
    modRuntimeOnly("dev.architectury:architectury-neoforge:${rootProject.architectury_api_version}")

    // Distant Horizons
    modRuntimeOnly("blank:DistantHorizons-fabric-neoforge-${rootProject.distant_horizons_version}-${rootProject.minecraft_version}")
}
